routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Auth::routes();
Route::get('/', 'GeneralController@index');

Route::get('/home', 'HomeController@index');
Route::resource('transactions','TransactionsController');
//payments
Route::resource('payments','PaymentController');

//admin-dashboard
Route::get('dashboard','DashboardController@index');
//bus-operators
Route::resource('bus-operators','BusOperatorController');
//routes
Route::resource('routes','RouteController');
//montlyplan
Route::resource('monthly-plan','MonthlyPlanController');
//tickets
Route::get('ticket','TicketController@buyTicket');
Route::post('ticket/buy','TicketController@payMent');
Route::post('ticket/fare','TicketController@getFare');
Route::get('ticket/my-tickets','TicketController@myTickets');

//monthly-plan
Route::post('monthly-plan/cost','PlanTransactionController@cost');
Route::post('monthly-plan/subscription','PlanTransactionController@monthlyPlanSubs');
//contact
Route::get('/contact','ContactController@index');
//about us
Route::get('/who-we-are','AboutController@whoWeAre');
Route::get('/our-team','AboutController@ourTeam');
//statements
Route::get('/statements','SinglePagesController@statements');
//user
Route::get('/edit-account','UserController@editUserAccount');
Route::post('/updateUserAccount','UserController@updateUserAccount');

resources/views/partials/admin-side-bar.blade.php
<div class="sidebar left sidebar-size-3 sidebar-offset-0 sidebar-visible-desktop sidebar-visible-mobile sidebar-skin-dark" id="sidebar-menu" data-type="collapse">
    <div data-scrollable>
        <div class="sidebar-block">
            <div class="profile">
                <a href="#">
                    <img src="{{asset('images/people/110/guy-6.jpg')}}" alt="people" class="img-circle width-80" />
                </a>
                <h4 class="text-display-1 margin-none">Instructor Name</h4>
            </div>
        </div>

        <ul class="sidebar-menu">
            <li class="hasSubmenu">
                <a href="#forum-menu"><i class="fa fa-bus"></i><span>Bus Operators</span></a>
                <ul id="forum-menu">
                    <li><a href="{{route('bus-operators.create')}}">
                            <span>Add Bus Operators</span>
                        </a>
                    </li>
                    <li><a href="app-forum-category.html">
                            <span>View All Buses</span>
                        </a>
                    </li>
                    <li><a href="app-forum-thread.html">
                            <span>Blacklisted Operators</span>
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>

resources/views/partials/footer.blade.php
<footer class="footer" onclick="showDemo()">
    Kenya Bus Demo <strong>Apps:Lab</strong> v1.1.0 &copy; Copyright 2016
</footer>
<script>
    function showDemo()
    {
        swal('Oops...', 'Something went wrong!', 'error');
    }
</script>

resources/views/partials/sidemenu.blade.php
<div class="panel panel-default" data-toggle="panel-collapse" data-open="true">
    <div class="panel-heading panel-collapse-trigger">
        <h4 class="text-headline margin-none">Quick Menu</h4>
    </div>
    <div class="panel-body list-group">
        <ul class="list-group list-group-menu">
            <li class="list-group-item "><a class="link-text-color" href="{{url('ticket/my-tickets')}}">My tickets</a></li>
            <li class="list-group-item "><a class="link-text-color" href="{{url('ticket')}}">Buy ticket</a></li>
            <li class="list-group-item"><a class="link-text-color" href="{{url('statements')}}">My account statement</a></li>
            <li class="list-group-item"><a class="link-text-color" href="{{url('payments')}}">My account payments</a></li>
            <li class="list-group-item"><a class="link-text-color" href="{{url('monthly-plan')}}">Monthly plans</a></li>
            <li class="list-group-item"><a class="link-text-color" href="website-instructor-earnings.html">Monthly plan: Multiple routes</a></li>
            {{--<li class="list-group-item"><a class="link-text-color" href="website-instructor-statement.html">Monthly plan: Group plan</a></li>--}}
            <li class="list-group-item"><a class="link-text-color" href="{{url('edit-account')}}">Edit Profile</a></li>
        </ul>
    </div>
</div>

<h4>Featured</h4>
<div class="slick-basic slick-slider" data-items="1" data-items-lg="1" data-items-md="1" data-items-sm="1" data-items-xs="1">

    <div class="item">
        <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
            <div class="panel-body">
                <div class="media media-clearfix-xs">
                    <div class="media-left">
                        <div class="cover width-90 width-100pc-xs overlay cover-image-full hover">
                            <span class="img icon-block s90 bg-lightred"></span>
                            <span class="overlay overlay-full padding-none icon-block s90 bg-lightred">
                        <span class="v-center">
                            <i class="fa fa-windows"></i>
                        </span>
                        </span>
                            <a href="website-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                          <span class="v-center">
                            <span class="btn btn-circle btn-red-500 btn-lg"><i class="fa fa-graduation-cap"></i></span>
                          </span>
                            </a>
                        </div>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading margin-v-5-3"><a href="website-course.html">Portable Environments with Vagrant</a></h4>
                        <p class="small margin-none">
                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                            <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                            <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="item">
        <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
            <div class="panel-body">
                <div class="media media-clearfix-xs">
                    <div class="media-left">
                        <div class="cover width-90 width-100pc-xs overlay cover-image-full hover">
                            <span class="img icon-block s90 bg-brown"></span>
                            <span class="overlay overlay-full padding-none icon-block s90 bg-brown">
                        <span class="v-center">
                            <i class="fa fa-wordpress"></i>
                        </span>
                        </span>
                            <a href="website-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                          <span class="v-center">
                            <span class="btn btn-circle btn-orange-500 btn-lg"><i class="fa fa-graduation-cap"></i></span>
                          </span>
                            </a>
                        </div>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading margin-v-5-3"><a href="website-course.html">WordPress Theme Development</a></h4>
                        <p class="small margin-none">
                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                            <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                            <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="item">
        <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
            <div class="panel-body">
                <div class="media media-clearfix-xs">
                    <div class="media-left">
                        <div class="cover width-90 width-100pc-xs overlay cover-image-full hover">
                            <span class="img icon-block s90 bg-purple"></span>
                            <span class="overlay overlay-full padding-none icon-block s90 bg-purple">
                        <span class="v-center">
                            <i class="fa fa-jsfiddle"></i>
                        </span>
                        </span>
                            <a href="website-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                          <span class="v-center">
                            <span class="btn btn-circle btn-purple-500 btn-lg"><i class="fa fa-graduation-cap"></i></span>
                          </span>
                            </a>
                        </div>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading margin-v-5-3"><a href="website-course.html">Modular JavaScript with Browserify</a></h4>
                        <p class="small margin-none">
                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                            <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                            <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="item">
        <div class="panel panel-default paper-shadow" data-z="0.5" data-hover-z="1" data-animated>
            <div class="panel-body">
                <div class="media media-clearfix-xs">
                    <div class="media-left">
                        <div class="cover width-90 width-100pc-xs overlay cover-image-full hover">
                            <span class="img icon-block s90 bg-default"></span>
                            <span class="overlay overlay-full padding-none icon-block s90 bg-default">
                        <span class="v-center">
                            <i class="fa fa-cc-visa"></i>
                        </span>
                        </span>
                            <a href="website-course.html" class="overlay overlay-full overlay-hover overlay-bg-white">
                          <span class="v-center">
                            <span class="btn btn-circle btn-white btn-lg"><i class="fa fa-graduation-cap"></i></span>
                          </span>
                            </a>
                        </div>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading margin-v-5-3"><a href="website-course.html">Easy Online Payments with Stripe</a></h4>
                        <p class="small margin-none">
                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                            <span class="fa fa-fw fa-star text-yellow-800"></span>
                            <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                            <span class="fa fa-fw fa-star-o text-yellow-800"></span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/partials/topbarmenu.blade.php
<!-- Fixed navbar -->
<div class="navbar navbar-default navbar-fixed-top navbar-size-large navbar-size-xlarge paper-shadow" data-z="0" data-animated role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <div class="navbar-brand navbar-brand-logo">
                <a href="index.html">
                    <img  class="svg"  src="{{asset('images/logo.png')}}" width="80%" height="60%" style="margin-top: 3px" alt="logo">
                </a>
            </div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="main-nav">
            <ul class="nav navbar-nav navbar-nav-margin-left">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">About Us</a>
                    <ul class="dropdown-menu">
                        <li><a href="{{url('who-we-are')}}">Who we are</a></li>
                        <li><a href="{{asset(url('our-team'))}}">Our Team</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" >How It Works</a>
                </li>
                <li class="dropdown">
                    <a href="{{url('/ticket')}}" >Bus Ticket</a>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Monthly Plan <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {{--<li class="active"><a href="website-student-dashboard.html">Daily plan</a></li>--}}
                        <li><a href="{{url('monthly-plan/create')}}">Monthly plan</a></li>
                        {{--<li><a href="website-course-forums.html">Monthly group plan</a></li>--}}
                        <li><a href="website-take-course.html">Monthly multiple routes plan</a></li>

                        {{--<li><a href="website-take-quiz.html">Take Quiz</a></li>--}}
                        {{--<li><a href="website-student-messages.html">Messages</a></li>--}}
                        {{--<li><a href="website-student-profile.html">Private Profile</a></li>--}}
                    </ul>
                </li>
                {{--<li class="dropdown">--}}
                    {{--<a href="#" class="dropdown-toggle" data-toggle="dropdown">FAQs</a>--}}
                {{--</li>--}}
                <li class="dropdown">
                    <a href="{{url('/contact')}}" >Contact Us</a>
                </li>
            </ul>
            <div class="navbar-right">
                @if (Auth::guest())
                    <a href="{{ url('/register') }}" class="navbar-btn btn btn-primary">Register</a>
                    <a href="{{ url('/login') }}" class="navbar-btn btn btn-success">Login</a>
                @else
                <ul class="nav navbar-nav navbar-nav-bordered navbar-nav-margin-right">
                    <!-- user -->
                    <li class="dropdown user active">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"  >
                            <img src="{{asset('images/people/110/guy-6.jpg')}}" alt="" class="img-circle" /> {{ Auth::user()->username }}<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li class="active"><a href="{{url('/')}}"><i class="fa fa-bar-chart-o"></i> My Account</a></li>
                            <li><a href="{{ url('/logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();"><i class="fa fa-sign-out"></i> Logout</a>
                                <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </li>
                        </ul>
                    </li>
                    <!-- // END user -->
                </ul>
                    <a href="{{route('transactions.create')}}" class="navbar-btn btn-sm btn btn-primary">Top Account</a>
                @endif

            </div>
        </div>
        <!-- /.navbar-collapse -->

    </div>
</div>

resources/views/partials/userdetailsbar.blade.php
<div class="parallax overflow-hidden bg-blue-400 page-section third">
    <div class="container parallax-layer" data-opacity="true">
        <div class="row">
            <div class="col-sm-12">
                <div class="media v-middle">
                    <div class="media-left text-center">
                        <a href="#">
                            <img src="images/people/110/guy-6.jpg" alt="people" class="img-circle width-80" />
                        </a>
                    </div>
                    <div class="media-body">
                        <h2 class="text-white text-display-1 margin-v-0">{{\Illuminate\Support\Facades\Auth::user()->name}}</h2>
                        <p class="text-subhead"><a class="link-white text-underline" href="website-student-public-profile.html"></a></p>
                    </div>
                    <div class="media-left">
                        <span class="label bg-blue-500">Current balance: Ksh  {{\App\Wallet::where('user_id',Auth::user()->id)->first()->balance}}</span>
                    </div>
                </div>
            </div>
            {{--<div class="col-sm-4">--}}
                {{--<div class="media v-middle">--}}
                    {{--<div class="media-left text-center">--}}
                        {{--<a href="#">--}}
                            {{--<img src="images/people/110/guy-6.jpg" alt="people" class="img-circle width-80" />--}}
                        {{--</a>--}}
                    {{--</div>--}}
                    {{--<div class="media-body">--}}
                        {{--<h1 class="text-white text-display-1 margin-v-0">Bill Smith</h1>--}}
                        {{--<p class="text-subhead"><a class="link-white text-underline" href="website-student-public-profile.html">View public profile</a></p>--}}
                    {{--</div>--}}
                    {{--<div class="media-right">--}}
                        {{--<span class="label bg-blue-500">Student</span>--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--</div>--}}
        </div>
    </div>
</div>