routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/
Auth::routes();
Route::get('/', 'GeneralController@index');

Route::get('/home', 'HomeController@index');
Route::resource('transactions','TransactionsController');
//payments
Route::resource('payments','PaymentController');

//admin-dashboard
Route::get('dashboard','DashboardController@index');
//bus-operators
Route::resource('bus-operators','BusOperatorController');
//routes
Route::resource('routes','RouteController');
//montlyplan
Route::resource('monthly-plan','MonthlyPlanController');
//tickets
Route::get('ticket','TicketController@buyTicket');
Route::post('ticket/buy','TicketController@payMent');
Route::post('ticket/fare','TicketController@getFare');
Route::get('ticket/my-tickets','TicketController@myTickets');

//monthly-plan
Route::post('monthly-plan/cost','PlanTransactionController@cost');
Route::post('monthly-plan/subscription','PlanTransactionController@monthlyPlanSubs');
//contact
Route::get('/contact','ContactController@index');
//about us
Route::get('/who-we-are','AboutController@whoWeAre');
Route::get('/our-team','AboutController@ourTeam');
//statements
Route::get('/statements','SinglePagesController@statements');
//user
Route::get('/edit-account','UserController@editUserAccount');
Route::post('/updateUserAccount','UserController@updateUserAccount');

app/Http/Controllers/TransactionsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\WalletRequest;
use App\Payment;
use App\Transaction;
use App\Wallet;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Kbs\TransactionRepo;

class TransactionsController extends Controller
{
    protected $wallet;
    protected $transaction;
    protected $payment;

    /**
     * TransactionsController constructor.
     * @param $wallet
     * @param $transaction
     * @param $payment
     */
    public function __construct(Wallet $wallet,Transaction $transaction,Payment $payment)
    {
        $this->wallet = $wallet;
        $this->transaction = $transaction;
        $this->payment = $payment;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return redirect('/');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('transactions.create')
            ->withWallet($this->wallet->where('user_id',Auth::user()->id)->first());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(WalletRequest $request)
    {
        $wallet_data = $this->wallet->where('user_id',Auth::user()->id)->first();
        $this->wallet->findorfail($wallet_data->id)->update(
            [
                'balance' => $request->topedamount + $wallet_data->balance
            ]
        );

        $this->transaction->create(
            [
                'user_id' => Auth::user()->id,
                'type' => Transaction::ACCOUNT_TOP_UP,
                'reference' => $request->reference,
                'service' => Transaction::ACCOUNT_TOP_UP,
                'description' => Transaction::ACCOUNT_TOP_UP,
                'from_acc' => 'M-Pesa',
                'to_acc' => $wallet_data->account_number,
                'status' => Transaction::COMPLETED,
                'amount' => env('MPESA_AMOUNT')
            ]);

        if ($request->has('ajax'))
        {
            if ($request->amount > Wallet::where('user_id',Auth::user()->id)->first()->balance)
            {
                return ['message' => 'FAIL'];
            }

            return ['message'=>'success',
                'amount'=>Wallet::where('user_id',Auth::user()->id)->first()->balance];
        }
        return Redirect::to('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/transactions/create.blade.php
@extends('layout')

@section('content')
    <div class="container">
        <div class="row" style="margin-top: 20px">
            @foreach($errors as $error)
                <p>{{$error}}</p>
            @endforeach
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading text-center"><h3>Top Up Account</h3></div>
                    <div class="panel-body">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <h4>Instructions</h4>
                                <ol>
                                    <li>Go to M-PESA Menu</li>
                                    <li>Select Pay Bill</li>
                                    <li>Enter 552552 as the Business Number</li>
                                    <li>Enter {{$wallet->account_number}} as the Account Number</li>
                                    <li>Enter the value amount to pay eg 3000 (NO COMMAS)</li>
                                    <li>Enter your M-PESA PIN</li>
                                    <li>Then send the request</li>
                                    <li>You will receive an SMS confirming the transaction</li>
                                    <li>Enter the M-PESA REFERENCE NUMBER below</li>
                                    <li>Click finish button below to finish</li>
                                </ol>
                            </div>
                        </div>

                        <form class="form-horizontal" role="form" method="POST" action="{{ route('transactions.store') }}">
                            {{ csrf_field() }}
                            <div class="col-md-10 col-md-offset-1">
                                <div class="form-group form-control-material static required {{ $errors->has('topedamount') ? ' has-error' : '' }}">
                                    <input id="topedamount" type="number" min="20" class="form-control" name="topedamount" value="{{ old('topedamount') }}" required autofocus>
                                    <label for="topedamount">Amount
                                    </label>
                                </div>
                                <div class="form-group form-control-material static required {{ $errors->has('reference') ? ' has-error' : '' }}">
                                    <input id="reference" type="text" class="form-control text-uppercase" name="reference" value="{{ old('reference') }}" required>
                                    <label for="reference">M-PESA REFERENCCE NUMBER
                                    </label>
                                </div>
                                <div class="form-group">
                                    {{--<div class="col-md-6 col-md-offset-3">--}}
                                    <button type="submit" class="btn pull-right btn-primary">
                                        Finish
                                    </button>
                                </div>
                                {{--</div>--}}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/transactions/statements.blade.php
@extends('layout')
@include('partials.userdetailsbar')
@section('content')
    <div class="container">
    <div class="page-section">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-9">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="text-headline margin-none">My Account Statements</h4>
                        </div>
                        <div class="panel-body">
                        <table data-toggle="data-table" class="table table-responsive" cellspacing="0" >
                            <thead>
                            <tr>
                                <th>Date</th>
                                <th>Reference No</th>
                                <th>Description</th>
                                <th>Type</th>
                                <th>Amount</th>
                            </tr>
                            </thead>
                            <tfoot>
                            <tr>
                                <th>Date</th>
                                <th>Reference No</th>
                                <th>Description</th>
                                <th>Type</th>
                                <th class="text-right">Amount</th>
                            </tr>
                            </tfoot>
                            <tbody>
                            @foreach($transactions as $transaction)
                            <tr>
                                <td><button class="btn btn-sm primary">{{\Carbon\Carbon::parse($transaction->created_at)->format('d-M-Y H:m')}}</button></td>
                                <td class="text-uppercase">{{ucwords($transaction->reference)}}</td>
                                <td>{{$transaction->description}}</td>
                                <td>{{ucwords($transaction->type)}}</td>
                                <td class="text-right">Ksh : {{$transaction->amount}}</td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                        <!-- // Data table -->
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
        @include('partials.sidemenu')
    </div>
            </div>
        </div>
    </div>
    </div>
    @include('partials.footer')
@endsection